/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2020-12-21 02:39:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.lecture;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.MemberVO;
import vo.ClassVO;
import vo.LectureVO;
import java.util.List;

public final class lecture_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

int Lec_title = 0;
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("vo.LectureVO");
    _jspx_imports_classes.add("vo.ClassVO");
    _jspx_imports_classes.add("vo.MemberVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("   <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<!--    <link rel=\"stylesheet\" href=\"../css/List_lec.css\" type=\"\"> -->\r\n");
      out.write("   <link href=\"https://fonts.googleapis.com/css?family=Lato\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("   <link href=\"https://fonts.googleapis.com/css?family=Montserrat\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("   <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("   <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("   <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("   <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("   body {\r\n");
      out.write("      font: 400 15px/1.8 Lato, sans-serif;\r\n");
      out.write("      min-width: 1800px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .isotope_filters a.active, .isotope_filters a:hover {\r\n");
      out.write("      border-color: #ffb20e;\r\n");
      out.write("      background-color: #ffb20e;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .isotope_filters a {\r\n");
      out.write("      font-weight: 400;\r\n");
      out.write("      border: 2px solid #1dbb90;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      background-color: #1dbb90;\r\n");
      out.write("      webkit-border-radius: 4px;\r\n");
      out.write("      moz-border-radius: 4px;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .isotope_filters a {\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      margin: 0 4px 4px 0;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      padding: .75em 1.5em;\r\n");
      out.write("      font-size: .75em;\r\n");
      out.write("      line-height: 1.3em;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .sc_blogger .isotope_filters {\r\n");
      out.write("      margin: 1.5em 0 1em;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .isotope_filters {\r\n");
      out.write("      overflow: hidden;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      padding-bottom: .5em;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .isotope_wrap .isotope_item .post_featured, .isotope_wrap .isotope_item_courses_1 .post_featured\r\n");
      out.write("      {\r\n");
      out.write("      border-color: #1eaace;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .isotope_wrap .isotope_item_courses .post_featured, .isotope_wrap .isotope_item_portfolio .post_featured,\r\n");
      out.write("      .isotope_wrap .isotope_item_square .post_featured, .isotope_wrap .isotope_item_grid .post_featured\r\n");
      out.write("      {\r\n");
      out.write("      border-bottom: 0;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .isotope_wrap .isotope_item .post_featured {\r\n");
      out.write("      margin-bottom: 0;\r\n");
      out.write("      border-bottom: 5px solid #f0f0f0;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   h3, h4, h5 {\r\n");
      out.write("      /* margin: 10px 0 30px 0; */\r\n");
      out.write("      font-size: 20px;\r\n");
      out.write("      color: black;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .\r\n");
      out.write("   #myNavbar {\r\n");
      out.write("      height: 600px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .navbar {\r\n");
      out.write("      font-family: Montserrat, sans-serif;\r\n");
      out.write("      padding-top: 10px;\r\n");
      out.write("      padding-bottom: 100px;\r\n");
      out.write("      background-color: white;\r\n");
      out.write("      border: 0;\r\n");
      out.write("      font-size: 15px !important;\r\n");
      out.write("      height: 130px;\r\n");
      out.write("      opacity: 0.9;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .navbar-nav {\r\n");
      out.write("      margin-right: 30px;\r\n");
      out.write("      float: right;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      color: black;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .navbar .navbar-brand {\r\n");
      out.write("      color: #339900 !important;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      margin: 5px;\r\n");
      out.write("      font-size: 70px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   .navbar-nav li a:hover {\r\n");
      out.write("      color: #339900 !important;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .navbar-nav li .{\r\n");
      out.write("      color: #339900 !important;\r\n");
      out.write("      background-color: #29292c !important;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .mySlides {\r\n");
      out.write("      color: white;\r\n");
      out.write("      font-weight: 400px;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      height: 200px;\r\n");
      out.write("      background: #343838;\r\n");
      out.write("      padding: 1px 40px 10px 320px;\r\n");
      out.write("      margin-top: 200px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .banner {\r\n");
      out.write("      font-size: 15px;\r\n");
      out.write("      font-family: sans-serif;\r\n");
      out.write("      font-weight: 10px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #band {\r\n");
      out.write("      /* margin-top: 135px; */\r\n");
      out.write("      height: 1000px;\r\n");
      out.write("      margin-left: 200px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .inited { /*새로 추가*/\r\n");
      out.write("      min-width: 220px;\r\n");
      out.write("      height: 120px;\r\n");
      out.write("      border: 5px solid white;\r\n");
      out.write("      background: white;\r\n");
      out.write("      font-size: 1.4em;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #left a:hover {\r\n");
      out.write("      color: gray;\r\n");
      out.write("      font-size: 1.5em;\r\n");
      out.write("      text-decoration: underline;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #cont {\r\n");
      out.write("/*       border: 5px solid red; */\r\n");
      out.write("      /* text-align: center; */\r\n");
      out.write("      float: left;\r\n");
      out.write("      height: auto;\r\n");
      out.write("      width: 55%;\r\n");
      out.write("      /* margin: 60px 60px; */\r\n");
      out.write("      margin-left: 400px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .list {\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      float: left;\r\n");
      out.write("      width: 300px;\r\n");
      out.write("      height: 250px;\r\n");
      out.write("      padding-left: 30px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #center {\r\n");
      out.write("      min-height: 946px;\r\n");
      out.write("      min-width: 90%;\r\n");
      out.write("/*       border: 5px solid green; */\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      float: left;\r\n");
      out.write("      /* margin-left: 100px; */\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #reply {\r\n");
      out.write("      /* border: 5px solid red; */\r\n");
      out.write("      float: left;\r\n");
      out.write("      height: auto;\r\n");
      out.write("      min-width: 51%;\r\n");
      out.write("      margin-top: 30px;\r\n");
      out.write("      padding-left: 30px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("/*     #right { */\r\n");
      out.write("/*       border: 5px solid red; */\r\n");
      out.write("/*       height: 946px; */\r\n");
      out.write("/*       min-width: 20%; */\r\n");
      out.write("/*       float: left; */\r\n");
      out.write("/*    }  */\r\n");
      out.write("   .ul {\r\n");
      out.write("      float: left;\r\n");
      out.write("      margin-left: 70px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .made {\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      /* text-align: left; */\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .footer {\r\n");
      out.write("      float: left;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      background: #011627;\r\n");
      out.write("      color: white;\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .mydona {\r\n");
      out.write("      background: #EE7785;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .bt {\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .lecture {\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      margin-left: 100px;\r\n");
      out.write("      border: 1px solid black;\r\n");
      out.write("      border-radius: 30px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #lec_img {\r\n");
      out.write("      width: 600px;\r\n");
      out.write("      height: 400px;\r\n");
      out.write("      border-radius: 30px;\r\n");
      out.write("      margin-left: 200px;\r\n");
      out.write("   }\r\n");
      out.write("   .lec_img {\r\n");
      out.write("      width: 200px;\r\n");
      out.write("      height: 100px;\r\n");
      out.write("      border-radius: 30px;\r\n");
      out.write("      /* margin-left: 200px; */\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #pri {\r\n");
      out.write("      font-size: 1.2em;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .title {\r\n");
      out.write("      font-size: 1.3em;\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("   }\r\n");
      out.write("   .getDetail_cont{\r\n");
      out.write("      border: 1px solid black;\r\n");
      out.write("      \r\n");
      out.write("   }\r\n");
      out.write("   .class{\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      \r\n");
      out.write("   }\r\n");
      out.write("   #img{\r\n");
      out.write("      width: 400px;\r\n");
      out.write("      height: 300px;\r\n");
      out.write("   \r\n");
      out.write("   }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body id=\"myPage\" data-spy=\"scroll\" data-target=\".navbar\" data-offset=\"50\">\r\n");
      out.write("   ");

      MemberVO memberVo = (MemberVO)session.getAttribute("mVo");
      // 서블릿에서 만들어서 보낸 데이터를 보여준다. - 강의 정보
      List<LectureVO> lectureList = (List<LectureVO>)request.getAttribute("lectureList");
      
      // 교육 과정
      List<ClassVO> lectureList2 = (List<ClassVO>)request.getAttribute("lectureList2");
      
   
      out.write("\r\n");
      out.write("   <nav class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <div class=\"navbar-header\">\r\n");
      out.write("               <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("                 <span class=\"icon-bar\"></span>\r\n");
      out.write("                 <span class=\"icon-bar\"></span>\r\n");
      out.write("                 <span class=\"icon-bar\"></span>                        \r\n");
      out.write("               </button>\r\n");
      out.write("               <a class=\"navbar-brand\" href=\"");
      out.print(request.getContextPath() );
      out.write("/main.do\"><strong>Learning Market💻</strong></a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("          </div>\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-center\">\r\n");
      out.write("              <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/main.do\">홈</a></li>\r\n");
      out.write("              <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/lecture/lectureList.do\">강의실</a></li>\r\n");
      out.write("              <li class=\"dropdown\">\r\n");
      out.write("                 <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"");
      out.print(request.getContextPath() );
      out.write("/board/QnABoard.do\">커뮤니티<span class=\"caret\"></span></a>\r\n");
      out.write("               <ul class=\"dropdown-menu\">\r\n");
      out.write("                  <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/QnABoard.do?board_no=2\">묻고 답하기</a></li>\r\n");
      out.write("                  <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/NoticeBoard.do?board_no=1\">공지사항</a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("              ");

               if(memberVo == null) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/loginForm.do\">마이페이지</a></li>\r\n");
      out.write("            ");
 
               } else {
            
      out.write("\r\n");
      out.write("            <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/memberInfo/mypageForm.do\">마이페이지</a></li>\r\n");
      out.write("            ");
      
               }
            
      out.write("\r\n");
      out.write("            <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/main/List_don.do\">재능기부</a></li>\r\n");
      out.write("            ");

               if(memberVo == null) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/loginForm.do\">로그인</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/joinForm.do\">회원가입</a></li>\r\n");
      out.write("            ");

               } else {
            
      out.write("\r\n");
      out.write("            <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logoutForm.do\">로그아웃</a></li>\r\n");
      out.write("            <li class=\"dropdown\">\r\n");
      out.write("               <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"");
      out.print(request.getContextPath());
      out.write("/basket/BasketList.do?mem_no=");
      out.print(memberVo.getMem_no() );
      out.write("\">\r\n");
      out.write("                  <img src = \"../images/바구니.png\" width = \"30px;\" height=\"25px;\"/><span class=\"caret\"></span></a>\r\n");
      out.write("               <ul class=\"dropdown-menu\">\r\n");
      out.write("                  <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/basket/BasketList.do?mem_no=");
      out.print(memberVo.getMem_no() );
      out.write("&state=1\">수강바구니</a></li>\r\n");
      out.write("                  <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/basket/BasketList.do?mem_no=");
      out.print(memberVo.getMem_no() );
      out.write("&state=2\">위시리스트</a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
      
               }
            
      out.write("\r\n");
      out.write("              <li class=\"dropdown\">\r\n");
      out.write("                 <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">MORE <span class=\"caret\"></span></a> \r\n");
      out.write("               <ul class=\"dropdown-menu\">\r\n");
      out.write("                  <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/NoticeBoard.do?board_no=1\">공지사항</a></li>\r\n");
      out.write("                  <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/main/main_intro.do\">소개</a></li>\r\n");
      out.write("                  <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/main/List_don.do\">재능기부신청</a></li>\r\n");
      out.write("                  <li><a href=\"#\">멤버십신청</a></li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("   </nav>\r\n");
      out.write("\r\n");
      out.write("   <!-- Container (The Band Section) -->\r\n");
      out.write("   <div class=\"mySlides\">\r\n");
      out.write("      ");

         

         for(LectureVO vo : lectureList){
            // 강의 코드를 변수에 저장
            Lec_title = vo.getLec_title();
      
      out.write("\r\n");
      out.write("      <br>\r\n");
      out.write("      <img class=\"lec_img\"src=\"");
      out.print(vo.getImage() );
      out.write("\"> \r\n");
      out.write("      <br><br>");
      out.print(vo.getLec_nm() );
      out.write("<br><br>\r\n");
      out.write("         \r\n");
      out.write("   </div>\r\n");
      out.write(" \r\n");
      out.write("     <div class=\"isotope_filters inited\">\r\n");
      out.write("      <br>\r\n");
      out.write("      <a href=\"");
      out.print(request.getContextPath() );
      out.write("/lecture/lectureList.do\" style=\"color: black\">All</a>\r\n");
      out.write("      <a href=\"");
      out.print(request.getContextPath() );
      out.write("/lecture/lectureList.do?cate=java\"  class=\"theme_button\">자바</a>\r\n");
      out.write("      <a href=\"");
      out.print(request.getContextPath() );
      out.write("/lecture/lectureList.do?cate=mysql\"  class=\"theme_button\">mysql</a>\r\n");
      out.write("      <a href=\"");
      out.print(request.getContextPath() );
      out.write("/lecture/lectureList.do?cate=html\"  class=\"theme_button\">HTML</a>\r\n");
      out.write("      <a href=\"");
      out.print(request.getContextPath() );
      out.write("/lecture/lectureList.do?cate=javaScript\"  class=\"theme_button\">javaScript</a>\r\n");
      out.write("      <a href=\"");
      out.print(request.getContextPath() );
      out.write("/lecture/lectureList.do?cate=jquery\"  class=\"theme_button\">jquery</a>\r\n");
      out.write("      <a href=\"");
      out.print(request.getContextPath() );
      out.write("/lecture/lectureList.do?cate=css\"  class=\"theme_button\">css</a>\r\n");
      out.write("      <a href=\"");
      out.print(request.getContextPath() );
      out.write("/lecture/lectureList.do?cate=python\"  class=\"theme_button\">python</a>\r\n");
      out.write("      <a href=\"");
      out.print(request.getContextPath() );
      out.write("/lecture/lectureList.do?cate=spring\"  class=\"theme_button\">spring</a>\r\n");
      out.write("      <a href=\"");
      out.print(request.getContextPath() );
      out.write("/lecture/lectureList.do?cate=Linux\"  class=\"theme_button\">Linux</a>\r\n");
      out.write("      <a href=\"");
      out.print(request.getContextPath() );
      out.write("/lecture/lectureList.do?cate=c\"  class=\"theme_button\">C언어</a>\r\n");
      out.write("    </div>\r\n");
      out.write(" \r\n");
      out.write("    <div id=\"center\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("         <p class=\"title\">강좌명</p><br>");
      out.print(vo.getLec_nm());
      out.write("<br><br>\r\n");
      out.write("           <ul class=\"nav nav-tabs\">\r\n");
      out.write("             <li class=\"active\"><a href=\"#\">Home</a></li>\r\n");
      out.write("             <li><a href=\"#lecture\"  class=\"theme_button\">강좌소개</a></li>\r\n");
      out.write("             <li><a href=\"#class\">교육과정</a></li>\r\n");
      out.write("             <li><a href=\"#\">수강후기</a></li>\r\n");
      out.write("           </ul><br>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"cont\">\r\n");
      out.write("\r\n");
      out.write("         <div id=\"lecture\">\r\n");
      out.write("<!--             <p class=\"title\">강의코드:</p> -->\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <!-- 해당 강의 이미지 넣을 곳 -->\r\n");
      out.write("             <img id=\"lec_img\"src=\"");
      out.print(vo.getImage() );
      out.write("\"> <br>\r\n");
      out.write("            ");
      out.print(vo.getCategory ());
      out.write("<br>\r\n");
      out.write("            ");
      out.print(vo.getIntro());
      out.write("<br><br>\r\n");
      out.write("            <p class=\"title\">결제금액</p><br>\r\n");
      out.write("            <p id=\"pri\">💸");
      out.print(vo.getPrice() );
      out.write("원</p><br><br>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"getDetail_cont\">\r\n");
      out.write("               <p class=\"title\">  📚 강의상세 내용</p><br>");
      out.print(vo.getDetail_cont   ());
      out.write("<br><br><br>\r\n");
      out.write("            </div>\r\n");
      out.write("         ");

         }
         
      out.write("\r\n");
      out.write("               <br>\r\n");
      out.write("               <p class=\"title\">  교육과정</p>\r\n");
      out.write("               <table class = \"CList\" border=\"1\" style=\"width:100%\">\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <th style=\"text-align:center;width:700px;\">단원명</th>  <th style=\"text-align:center;\">교육영상</th> <th style=\"width:100px;text-align:center;\">&nbsp;</th>\r\n");
      out.write("               </tr>\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("               ");

               int cnt=0;
               for(ClassVO vo2 : lectureList2){
               
      out.write("\r\n");
      out.write("               <tr>\r\n");
      out.write("               ");
   
                  cnt++;
                  if(vo2.getClass_nm().contains(".0.0.")){
                     String result = vo2.getClass_nm().substring(vo2.getClass_nm().lastIndexOf(".")+1);
               
      out.write("\r\n");
      out.write("                  <td>");
      out.print(cnt+". "+result);
      out.write("</td>\r\n");
      out.write("               ");

                  }else{
               
      out.write("\r\n");
      out.write("                  <td>");
      out.print(vo2.getClass_nm() );
      out.write("</td>\r\n");
      out.write("               ");

                  }
                  if(vo2.getVideo()!=null) { 
               
      out.write("\r\n");
      out.write("            \r\n");
      out.write("                  <td>");
      out.print(vo2.getVideo() );
      out.write("</td>\r\n");
      out.write("               ");
 
                  }
               
      out.write("\r\n");
      out.write("               \r\n");
      out.write("\r\n");
      out.write("         <!-- <P>교육과정</P> -->\r\n");
      out.write("            \r\n");
      out.write("            <td style=\"text-align:center;\">\r\n");
      out.write("            ");

               if( memberVo != null && memberVo.getMem_no() == lectureList.get(0).getMem_no()) {
            
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <form class=\"class\" action=\"");
      out.print(request.getContextPath());
      out.write("/lecture/classUpdateForm.do\" method=\"post\">\r\n");
      out.write("               <input type=\"hidden\" name = \"Class_list\" value=\"");
      out.print(vo2.getClass_list());
      out.write("\">\r\n");
      out.write("               <input type=\"hidden\" name = \"Lec_title\" value=\"");
      out.print(vo2.getLec_title());
      out.write("\">\r\n");
      out.write("               <input type=\"hidden\" name = \"Class_nm\" value=\"");
      out.print(vo2.getClass_nm());
      out.write("\">\r\n");
      out.write("               <input type=\"hidden\" name = \"Video\" value=\"");
      out.print(vo2.getVideo());
      out.write("\">\r\n");
      out.write("               <input type=\"submit\" value=\"단원수정\">\r\n");
      out.write("            </form><br>\r\n");
      out.write("         ");

               }
         
      out.write("\r\n");
      out.write("            </td>\r\n");
      out.write("         ");
    
            }
         
      out.write("\r\n");
      out.write("         </tr>\r\n");
      out.write("         \r\n");
      out.write("         ");

         if(memberVo != null && memberVo.getMem_no() == lectureList.get(0).getMem_no()) {
         
      out.write("\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td style=\"text-align:right; border-right-color: white; padding-right:5px;\">\r\n");
      out.write("         ");

            if(Lec_title != 0){ 
         
      out.write("\r\n");
      out.write("         <form action=\"");
      out.print(request.getContextPath());
      out.write("/lecture/classInsertForm.do\" method=\"post\">\r\n");
      out.write("            <input type=\"hidden\" name = \"Lec_title\" value=\"");
      out.print(Lec_title);
      out.write("\">\r\n");
      out.write("            <input type=\"submit\" value=\"단원작성\">\r\n");
      out.write("         </form>\r\n");
      out.write("         ");

         }
         
      out.write("\r\n");
      out.write("            </td>\r\n");
      out.write("            <td style=\"text-align:left; border-left-color: white; padding-left:5px;\">\r\n");
      out.write("         ");
 
            for(LectureVO vo : lectureList){   
         
      out.write("            \r\n");
      out.write("            <form action=\"");
      out.print(request.getContextPath());
      out.write("/lecture/lectureUpdateForm.do\" method=\"post\">\r\n");
      out.write("               <input type=\"hidden\" name = \"Lec_title\" value=\"");
      out.print(vo.getLec_title());
      out.write("\">\r\n");
      out.write("               <input type=\"hidden\" name = \"Mem_no\" value=\"");
      out.print(vo.getMem_no());
      out.write("\">\r\n");
      out.write("               <input type=\"hidden\" name = \"Intro\" value=\"");
      out.print(vo.getIntro());
      out.write("\">\r\n");
      out.write("               <input type=\"hidden\" name = \"Lec_nm\" value=\"");
      out.print(vo.getLec_nm());
      out.write("\">\r\n");
      out.write("               <input type=\"hidden\" name = \"Price\" value=\"");
      out.print(vo.getPrice());
      out.write("\">\r\n");
      out.write("               <input type=\"hidden\" name = \"Detail_cont\" value=\"");
      out.print(vo.getDetail_cont());
      out.write("\">\r\n");
      out.write("               <input type=\"hidden\" name = \"Preview_video\" value=\"");
      out.print(vo.getPreview_video());
      out.write("\">\r\n");
      out.write("               <input type=\"submit\" value=\"강의수정\">\r\n");
      out.write("            </form>\r\n");
      out.write("         ");

            }
         
      out.write("\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         ");

         }
         
      out.write("   \r\n");
      out.write("      \r\n");
      out.write("      </table>\r\n");
      out.write("      \r\n");
      out.write("         </div>\r\n");
      out.write(" \r\n");
      out.write("         <script type=\"text/javascript\">\r\n");
      out.write("            $(function(){\r\n");
      out.write("               // 장바구니에 등록된 강좌여부를 확인해서 '결제하기' 또는 '수강바구니담기'버튼이 나오게하는 Ajax처리   \r\n");
      out.write("               $.ajax({\r\n");
      out.write("                  url: \"");
      out.print(request.getContextPath());
      out.write("/basket/basketCount.do\",\r\n");
      out.write("                  data : { \"lec_title\" : \"");
      out.print(lectureList.get(0).getLec_title());
      out.write("\" ,\r\n");
      out.write("                        \"mem_no\" : \"");
      out.print(memberVo.getMem_no());
      out.write("\"},\r\n");
      out.write("                  success : function(res){\r\n");
      out.write("         \r\n");
      out.write("                     if(res.cnt==0){      // 수강바구니에 해당 강의가 없는 경우\r\n");
      out.write("                        $(\"#basketList\").show();\r\n");
      out.write("                        $(\"#wishList\").show();\r\n");
      out.write("                     }else{            // 수강바구니에 해당 강의가 등록되어 있는 경우\r\n");
      out.write("                        $(\"#basketList\").hide();\r\n");
      out.write("                        $(\"#wishList\").hide();\r\n");
      out.write("                     }\r\n");
      out.write("                  },\r\n");
      out.write("                  error : function(xhr){\r\n");
      out.write("                     alert(xhr.status);\r\n");
      out.write("                  },\r\n");
      out.write("                  dataType :'json'\r\n");
      out.write("               });\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("            });\r\n");
      out.write("         </script>\r\n");
      out.write("\r\n");
      out.write("         ");

         
            if(memberVo != null && (memberVo.getAut() == 3 || memberVo.getAut()==2)) {
         
      out.write("\r\n");
      out.write("         <div id=\"basketList\" style=\"display:none;\">\r\n");
      out.write("            <form action=\"");
      out.print(request.getContextPath());
      out.write("/basket/basketInsert.do\" method=\"post\">\r\n");
      out.write("               <input type=\"hidden\" name = \"lec_title\" value=\"");
      out.print(lectureList.get(0).getLec_title() );
      out.write("\">\r\n");
      out.write("               <input type=\"hidden\" name = \"mem_no\" value=\"");
      out.print(memberVo.getMem_no());
      out.write("\">\r\n");
      out.write("               <input type=\"hidden\" name = \"state\" value=\"1\">\r\n");
      out.write("               <input type=\"submit\" id=\"btnCart\"  value=\"수강바구니에 담기\">\r\n");
      out.write("            </form>\r\n");
      out.write("         </div>\r\n");
      out.write("      \r\n");
      out.write("         <div id=\"wishList\"  style=\"display:none;\">\r\n");
      out.write("            <form action=\"");
      out.print(request.getContextPath());
      out.write("/basket/basketInsert.do\" method=\"post\">\r\n");
      out.write("               <input type=\"hidden\" name = \"lec_title\" value=\"");
      out.print(lectureList.get(0).getLec_title() );
      out.write("\">\r\n");
      out.write("               <input type=\"hidden\" name = \"mem_no\" value=\"");
      out.print(memberVo.getMem_no());
      out.write("\">\r\n");
      out.write("               <input type=\"hidden\" name = \"state\" value=\"2\">\r\n");
      out.write("               <input type=\"submit\" id=\"btnCart\"  value=\"위시리스트에 담기\">\r\n");
      out.write("            </form>\r\n");
      out.write("         </div>\r\n");
      out.write("         ");

            }
         
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <div id=\"right\">\r\n");
      out.write("   \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("   <footer class=\"footer\">\r\n");
      out.write("      <div class=\"ul\">\r\n");
      out.write("         <ul>\r\n");
      out.write("            <li>러닝마켓</li>\r\n");
      out.write("            <li>LM소개</li>\r\n");
      out.write("\r\n");
      out.write("         </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"ul\">\r\n");
      out.write("         <ul>\r\n");
      out.write("            <li><a>고객센터</a></li>\r\n");
      out.write("            <li>이용약관</li>\r\n");
      out.write("            <li>개인정보취급방침</li>\r\n");
      out.write("         </ul>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"ul\">\r\n");
      out.write("         <ul>\r\n");
      out.write("            <li><a>커뮤니티</a></li>\r\n");
      out.write("            <li>묻고답하기</li>\r\n");
      out.write("\r\n");
      out.write("         </ul>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <br> <br> <br> <br>\r\n");
      out.write("      <p class=\"made\">\r\n");
      out.write("         Learning Made By <a href=\"https://www.w3schools.com\"\r\n");
      out.write("            data-toggle=\"tooltip\" title=\"Visit w3schools\">대덕인재개발원</a>\r\n");
      out.write("         (주)Learning Market 사업자 정보<br> (주)Learning Market | 대표자 : 유동기\r\n");
      out.write("         |사업자번호 : 000-0000-0000 사업자 정보 확인 | 개인정보보호책임자 : 유동기 | 통신판매업\r\n");
      out.write("         :2020-중구대흥동 A-0001<br> 주소 : 대전광역시 중구 대흥동 500 영민빌딩 4층 402호 | 이메일\r\n");
      out.write("         : Learning Market@korea.com<br>\r\n");
      out.write("      </p>\r\n");
      out.write("\r\n");
      out.write("   </footer>\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
