/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2020-12-21 02:07:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Learning Market : 로그인</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.inflearn.com/dist/css/MAIN.29d84df994a8cbea6130.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"modal\">\r\n");
      out.write("<div class=\"dimmed\">\r\n");
      out.write("</div>\r\n");
      out.write("<section class=\"signin_modal\">\r\n");
      out.write("  <header class=\"header\">\r\n");
      out.write(" \r\n");
      out.write("  <button type=\"button\">❌</button>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\t\t<form class=\"main_form\" action=\"");
      out.print(request.getContextPath());
      out.write("/member/login.do\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<label class=\"atom_field\"> \r\n");
      out.write("\t\t\t<span class=\"label visually_hidden\">아이디</span> \r\n");
      out.write("\t\t\t<input class=\"input id\" type=\"text\" autofocus=\"true\" placeholder=\"아이디\" name=\"mem_id\" id=\"mem_id\"> \r\n");
      out.write("\t\t\t</label> \r\n");
      out.write("\t\t\t<label class=\"atom_field\"> \r\n");
      out.write("\t\t\t<span class=\"label visually_hidden\">비밀번호</span> \r\n");
      out.write("\t\t\t<input class=\"input pwd\" type=\"password\" placeholder=\"비밀번호\" name=\"mem_pass\" id=\"mem_pass\">\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"로그인\" class=\"atom_button button signin e-confirm\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"sub_form\"><p>비밀번호를 잊어버리셨나요?</p> <a class=\"find_password\">비밀번호 찾기</a></div>\r\n");
      out.write("  <div class=\"footer_form\">\r\n");
      out.write("    <div class=\"social\">\r\n");
      out.write("      <a rel=\"noreferrer noopener\" class=\"button facebook_auth oauth2\" data-type=\"facebook\" href=\"https://facebook.com/dialog/oauth?response_type=code&amp;client_id=1101702136522636&amp;redirect_uri=https%3A%2F%2Fwww.inflearn.com%2Fauth%2Ffacebook&amp;scope=email\">\r\n");
      out.write("        <i class=\"fab fa-facebook-f\"></i><span>페이스북 로그인</span>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a rel=\"noreferrer noopener\" class=\"button google_auth oauth2\" data-type=\"google\" href=\"https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&amp;prompt=consent&amp;scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&amp;response_type=code&amp;client_id=887875630717-ror9t8ig4obhvokdij07eoochpqbu5kf.apps.googleusercontent.com&amp;redirect_uri=https%3A%2F%2Fwww.inflearn.com%2Fauth%2Fgoogle\">\r\n");
      out.write("        <i class=\"fab fa-google\"></i><span>구글 로그인</span>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a rel=\"noreferrer noopener\" class=\"button github_auth\" data-type=\"github\" href=\"https://github.com/login/oauth/authorize?response_type=code&amp;client_id=5fd8e44b142806d9cbea&amp;redirect_uri=https%3A%2F%2Fwww.inflearn.com%2Fauth%2Fgithub&amp;scope=user%3Aemail\">\r\n");
      out.write("        <i class=\"fab fa-github\"></i><span>깃허브 로그인</span>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a rel=\"noreferrer noopener\" class=\"button apple_auth oauth2\" data-type=\"apple\" href=\"https://appleid.apple.com/auth/authorize?client_id=com.inflab.inflearn.web&amp;redirect_uri=https://www.inflearn.com/auth/apple&amp;response_type=code id_token&amp;scope=email%20name&amp;response_mode=form_post\">\r\n");
      out.write("        <i class=\"fab fa-apple\"></i><span>애플 로그인</span>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"sub_form\"><p>Learning Market 회원이 아니신가요?</p>\r\n");
      out.write(" \t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/join.do\">회원가입하기</a>\r\n");
      out.write(" \t</div>\r\n");
      out.write("</section>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
