/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2020-12-21 02:07:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.MemberVO;

public final class List_005fdon_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("vo.MemberVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/List_don.css\" type=\"\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Lato\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Montserrat\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/js/memberJoinCheck.js\"></script>\r\n");
      out.write("<script>\t\r\n");
      out.write("\tvar id = ");
      out.print( session.getAttribute("id") );
      out.write(";\r\n");
      out.write("\t\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t\t $('#reportbtn').on('click', function() {\r\n");
      out.write("\t\t\t\t$('#rpModal').modal('show');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t /*\t\t\t\r\n");
      out.write(" \t\t\t //제출 버튼을 눌렀을 때\r\n");
      out.write("\t\t\t$('.btn-success').on(\"submit\", function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar memId = $(\"#mem_id\").val();\r\n");
      out.write("\t\t\t\tvar memCallmail = $(\"#mem_callmail\").val(); \r\n");
      out.write("\t\t\t\tvar memNm = $(\"#mem_nm\").val();\r\n");
      out.write("\t\t\t\tvar donConact = $(\"#don_conact\").val(); \r\n");
      out.write("\t\t\t\tvar memField = $(\"#mem_field\").val(); \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t \t\t}); */\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("#cover {\r\n");
      out.write("    width: 550px;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("\tpadding: 12px 24px;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("}\r\n");
      out.write(".modal_header h2 {\r\n");
      out.write("\tfont-size: 24px;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("\tmargin: 10px;\r\n");
      out.write("\tline-height: normal;\r\n");
      out.write("}\r\n");
      out.write(".modal_header .special {\r\n");
      out.write("    box-shadow: inset 0 -15px 0 #b6f6d6;\r\n");
      out.write("}\r\n");
      out.write(".form-group {\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write(".form-group label {\r\n");
      out.write("    display: block;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    font-family: 'Noto Sans KR';\r\n");
      out.write("    color: #595959;\r\n");
      out.write("    margin-bottom: 8px;\r\n");
      out.write("}\r\n");
      out.write("input[type=text] {\r\n");
      out.write("    padding: 10px 16px;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    border: 1px solid #dedede;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 90%;\r\n");
      out.write("}\r\n");
      out.write(".form-group textarea {\r\n");
      out.write("    padding: 10px 16px;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    border: 1px solid #dedede;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    resize: none;\r\n");
      out.write("    min-height: 250px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal_footer {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    padding: 10px 0;\r\n");
      out.write("    margin-top : 45px;\r\n");
      out.write("}\r\n");
      out.write("/* .btn-success { */\r\n");
      out.write("/*     display: flex; */\r\n");
      out.write("/*     align-items: center; */\r\n");
      out.write("/*     justify-content: center; */\r\n");
      out.write("/*     padding: 12px 32px; */\r\n");
      out.write("/*     font-size: 15px; */\r\n");
      out.write("/*     font-weight: 700; */\r\n");
      out.write("/*     background-color: #1dc078; */\r\n");
      out.write("/*     color: #fff; */\r\n");
      out.write("/*     box-shadow: 0 0 4px 0 rgba(0,0,0,.24); */\r\n");
      out.write("/* } */\r\n");
      out.write("btn btn-success\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"myPage\" data-spy=\"scroll\" data-target=\".navbar\" data-offset=\"50\">\r\n");
      out.write("\t");
MemberVO memberVo = (MemberVO)session.getAttribute("mVo");
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"");
      out.print(request.getContextPath() );
      out.write("/main.do\"><strong>Learning\tMarket💻</strong></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\"></div>\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-center\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/main.do\">홈</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/lecture/lectureList.do\">강의실</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"dropdown\" href=\"");
      out.print(request.getContextPath() );
      out.write("/board/QnABoard.do\">커뮤니티<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/QnABoard.do?board_no=2\">묻고 답하기</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/NoticeBoard.do?board_no=1\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t");

					if(memberVo == null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/loginForm.do\">마이페이지</a></li>\r\n");
      out.write("\t\t\t\t");

					} else if (memberVo.getAut() == 9){
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/manager/memberList.do\">관리페이지</a></li>\r\n");
      out.write("\t\t\t\t");
 
					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/memberInfo/mypageForm.do\">마이페이지</a></li>\r\n");
      out.write("\t\t\t\t");
		
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/main/List_don.do\">재능기부</a></li>\r\n");
      out.write("\t\t\t\t");

					if(memberVo == null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/loginForm.do\">로그인</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/joinForm.do\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logoutForm.do\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"");
      out.print(request.getContextPath());
      out.write("/basket/BasketList.do?mem_no=");
      out.print(memberVo.getMem_no() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<img src = \"../images/바구니.png\" width = \"30px;\" height=\"25px;\"/><span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/basket/BasketList.do?mem_no=");
      out.print(memberVo.getMem_no() );
      out.write("&state=1\">수강바구니</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/basket/BasketList.do?mem_no=");
      out.print(memberVo.getMem_no() );
      out.write("&state=2\">위시리스트</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t");
		
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">MORE <span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/NoticeBoard.do?board_no=1\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/main/main_intro.do\">소개</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/main/List_don.do\">재능기부신청</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">멤버십신청</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"band\"> \r\n");
      out.write("\t\t<div id=\"center\">\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/DonBoard.do?board_no=3\">재능기부 게시판</a>\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("<!-- \t\t\t<input id=\"reportbtn\" type='button' value='재능기부 신청하기' > -->\r\n");
      out.write("\t\t\t<!-- 베너 -->\r\n");
      out.write("\t\t\t<img id=\"img1\" src=\"../images/지식3.png\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"cont\">\r\n");
      out.write("\t\t\t<img id=\"img\" src=\"../images/재능기부.PNG\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"cont\">\r\n");
      out.write("\t\t\t<h2 id=\"h2\">\r\n");
      out.write("\t\t\t\t<strong>🧩지식공유자가 되어주세요!</strong>\r\n");
      out.write("\t\t\t</h2>\r\n");
      out.write("\t\t\t<img id=\"img2\" src=\"../images/재능기부2.PNG\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t <div class=\"mySlides\">\r\n");
      out.write("\t\t<h2>나의 재능에 가치를 기부하세요</h2>\r\n");
      out.write("\t\t<input id = \"reportbtn\" class=\"btn btn-success\" type='button' value='재능기부 신청하기'>\r\n");
      out.write("\t\t<div class=\"dona\">\r\n");
      out.write("\t\t\t온라인 강의로만 3억원!(1년간 실 수령액)<br> 나의 재능을 나눠 사람들에게 배움의 기회를 주고, 의미있는\r\n");
      out.write("\t\t\t대가를 가져가세요<br> Learning Market은 나만의 재능으로 의미있는 수익과 공유가 가능한 한국 유일한\r\n");
      out.write("\t\t\t플랫폼입니다.<br> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"w3-center\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t<footer class=\"footer\">\r\n");
      out.write("\t\t<div class=\"ul\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>러닝마켓</li>\r\n");
      out.write("\t\t\t\t<li>LM소개</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"ul\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a>고객센터</a></li>\r\n");
      out.write("\t\t\t\t<li>이용약관</li>\r\n");
      out.write("\t\t\t\t<li>개인정보취급방침</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"ul\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a src=\"\">커뮤니티</a></li>\r\n");
      out.write("\t\t\t\t<li>묻고답하기</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<br> <br> <br> <br>\r\n");
      out.write("\t\t<p class=\"made\">\r\n");
      out.write("\t\t\tLearning Made By <a href=\"https://www.w3schools.com\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"tooltip\" title=\"Visit w3schools\">대덕인재개발원</a>\r\n");
      out.write("\t\t\t(주)Learning Market 사업자 정보<br> (주)Learning Market | 대표자 : 유동기\r\n");
      out.write("\t\t\t|사업자번호 : 000-0000-0000 사업자 정보 확인 | 개인정보보호책임자 : 유동기 | 통신판매업\r\n");
      out.write("\t\t\t:2020-중구대흥동 A-0001<br> 주소 : 대전광역시 중구 대흥동 500 영민빌딩 4층 402호 | 이메일\r\n");
      out.write("\t\t\t: Learning Market@korea.com<br>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t\r\n");
      out.write("\t");

					if(memberVo != null) {
	
      out.write("\r\n");
      out.write("<!-- Modal(재능기부 요청안) -->\r\n");
      out.write("\t<div id=\"rpModal\" class=\"modal fade\" role=\"dialog\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t  <div class=\"modal-content\" id=\"cover\">\r\n");
      out.write("\t\t    <div class=\"modal_header\">\r\n");
      out.write("\t\t      <h3><button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button></h3>    \r\n");
      out.write("\t\t\t\t\t<h2>감사합니다,&nbsp; ");
      out.print(memberVo.getMem_id() );
      out.write("님<br> \r\n");
      out.write("\t\t\t\t\t<span class=\"special\">재능기부자가 되기 위해서</span><br> 아래 정보가 필요해요.\r\n");
      out.write("\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<form name=\"rpform\" id=\"rpform\" method=\"post\" action=\"");
      out.print(request.getContextPath());
      out.write("/main/Listdon_apply.do\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" id=\"mem_no\" name=\"mem_no\" value=\"");
      out.print( memberVo.getMem_no() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>아이디</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"mem_id\" value=\"");
      out.print(memberVo.getMem_id());
      out.write("\" disabled>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>연락받을 이메일</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"mem_callmail\" id=\"mem_callmail\" placeholder=\"자주 사용하는 이메일을 입력해주세요.\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>나를 소개하는 글</label>\r\n");
      out.write("\t\t\t\t\t\t\t<textarea class=\"form-control\" rows=\"5\" name=\"don_conact\" id=\"don_conact\" placeholder=\"지식공유자님을 간단하게 소개해 주세요 :)\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t      <label>희망 분야</label>\r\n");
      out.write("\t\t\t\t\t        <input type=\"text\" class=\"form-control\" name=\"mem_field\" id=\"mem_field\" placeholder=\"(예시) IT프로그래밍  /크리에이티브 / 업무스킬\">\t\t\t\t\t        \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal_footer\">\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t   <button type=\"submit\" class=\"btn btn-success\">제출</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t");

					}
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
