/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2020-12-21 03:49:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.ReplyVO;
import vo.PostVO;
import java.util.List;
import vo.MemberVO;

public final class DonBoardView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("vo.MemberVO");
    _jspx_imports_classes.add("vo.PostVO");
    _jspx_imports_classes.add("vo.ReplyVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t");

				PostVO postVo = (PostVO)request.getAttribute("boardView");
	
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/List_don.css\" type=\"text/css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Lato\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Montserrat\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/List_com.css\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar board_no = \"\";\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\tboard_no = $(\"#board_no\").val();\r\n");
      out.write("\t\t\t$('#addbtn').on('click', function() {\r\n");
      out.write("\t\t\t\tconsole.log($(\"#board_no\").val());\r\n");
      out.write("\t\t\t\tlocation.href='");
      out.print(request.getContextPath());
      out.write("/board/donBoardAddForm.do?board_no='+board_no;\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar id = ");
      out.print( session.getAttribute("id") );
      out.write(";\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$('#Deletebtn').on('click', function(){\r\n");
      out.write("\t\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/board/BoardDelete.do?board_no=");
      out.print(request.getAttribute("board_no"));
      out.write("&post_no=");
      out.print(request.getAttribute("post_no"));
      out.write("\";\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t$('#Updatebtn').on('click', function() {\r\n");
      out.write("\t\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/board/BoardUpdateForm.do?board_no=");
      out.print(request.getAttribute("board_no"));
      out.write("&post_no=");
      out.print(request.getAttribute("post_no"));
      out.write("\";\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t$('#reportbtn').on('click', function() {\r\n");
      out.write("\t\t\t\t$('#rpModal').modal('show');\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#rpSend').on('click', function() {\r\n");
      out.write("\t\t\t\t$('#rpModal').modal('hide');\r\n");
      out.write("\t\t\t\talert(\"신고 접수 되었습니다.\");\r\n");
      out.write("\t\t\t\t$('#rpform rpCont').val(\"\");\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"myPage\" data-spy=\"scroll\" data-target=\".navbar\" data-offset=\"50\">\r\n");
      out.write("\t");
MemberVO memberVo = (MemberVO)session.getAttribute("mVo");
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"");
      out.print(request.getContextPath() );
      out.write("/main.do\"><strong>Learning\tMarket💻</strong></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\"></div>\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-center\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/main.do\">홈</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#mylecture\">강의실</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"dropdown\" href=\"");
      out.print(request.getContextPath() );
      out.write("/board/QnABoard.do\">커뮤니티<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/QnABoard.do?board_no=2\">묻고 답하기</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/NoticeBoard.do?board_no=1\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t");

					if(memberVo == null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/loginForm.do\">마이페이지</a></li>\r\n");
      out.write("\t\t\t\t");

					} else if (memberVo.getAut() == 9){
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/manager/memberList.do\">관리페이지</a></li>\r\n");
      out.write("\t\t\t\t");
 
					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/memberInfo/mypageForm.do\">마이페이지</a></li>\r\n");
      out.write("\t\t\t\t");
		
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/main/List_don.do\">재능기부</a></li>\r\n");
      out.write("\t\t\t\t");

					if(memberVo == null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/loginForm.do\">로그인</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/joinForm.do\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logoutForm.do\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/basket/BasketList.do?mem_no=");
      out.print(memberVo.getMem_no() );
      out.write("\">장바구니</a></li>\r\n");
      out.write("\t\t\t\t");
		
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">MORE <span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/main/main_intro.do\">소개</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">재능기부신청</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">멤버십신청</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t\t\t<!-- 베너 -->\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"band\">\r\n");
      out.write("\t\t<div class=\"mySlides\"><br>\r\n");
      out.write("    \t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id = \"center\" style=\"border: solid 2px green;\"><br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<hr><span id = \"abc\">\r\n");
      out.write("\t\t\t\t");
 if(memberVo != null){ 
				if(memberVo.getMem_no() == postVo.getMem_no()) { 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/board/donBoardUpdateForm.do\" method=\"post\" id=\"up\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"board_no\" value=\"3\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"post_no\" value=\"");
      out.print(postVo.getPost_no());
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"post_cont\" value=\"");
      out.print(postVo.getPost_cont());
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"post_title\" value=\"");
      out.print(postVo.getPost_title() );
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"do_video\" value=\"");
      out.print(postVo.getDo_video());
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"수정\"> \r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\t<input type = \"button\" value = \"삭제\" id = \"Deletebtn\">\r\n");
      out.write("\t\t\t\t");
 } 
				}
      out.write("\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<div class = \"don_cont\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h1>");
      out.print(postVo.getPost_title() );
      out.write("</h1>\r\n");
      out.write("\t\t\t<hr style = \"border: solid 1px black;\">\r\n");
      out.write("\t\t\t작성자 : ");
      out.print(postVo.getNick_name() );
      out.write(" &nbsp; &nbsp; &nbsp;  작성일 : ");
      out.print(postVo.getPost_date() );
      out.write("\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t");
      out.print(postVo.getPost_cont());
      out.write("<br><br><br><br><br><br>\r\n");
      out.write("\t\t\t");
if(postVo.getDo_video()!=null){
      out.write("\r\n");
      out.write("\t\t\t<div class = \"don_cont\">\r\n");
      out.write("\t\t\t   <video muted autoplay loop>\r\n");
      out.write("      \t\t\t<source src=\"http://192.168.42.37/Test/donvideo/");
      out.print(postVo.getDo_video());
      out.write("\" type=\"video/mp4\">\r\n");
      out.write("    \t\t\t</video>\r\n");
      out.write("    \t\t\t</div><br>\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id = \"re\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

				if(memberVo != null){
			
      out.write("\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t \t\t<form id = \"replyAddform\" method = \"post\"  action=\"");
      out.print(request.getContextPath() );
      out.write("/board/ReplyAdd.do?board_no=");
      out.print(request.getAttribute("board_no"));
      out.write("&post_no=");
      out.print(request.getAttribute("post_no"));
      out.write("\" style=\"margin-left: 150px;\">\r\n");
      out.write("\t\t\t\t\t<h3>댓글 작성</h3>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"mem_no\" name=\"mem_no\" value = \"");
      out.print(memberVo.getMem_no() );
      out.write("\"/>\r\n");
      out.write("\t\t \t\t\t<textarea rows = \"5\" cols = \"80\" id = \"reply_cont\" name = \"reply_cont\"></textarea>\r\n");
      out.write("\t\t \t\t\t<br><input type = \"submit\" value = \"댓글 등록\" id = \"replyAdd\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t");
	} 
      out.write("\r\n");
      out.write("\t\t \t\t<hr>\r\n");
      out.write(" \t\t\r\n");
      out.write("\t\t\t \t<h4 id = \"replys\">댓글 목록\r\n");
      out.write("\t\t\t \t<table class = \"BList\">\r\n");
      out.write("\t\t\t \t\t<tr>\r\n");
      out.write("\t\t\t \t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t\t\t\t<th class = \"title\">내용</th>\r\n");
      out.write("\t\t\t\t\t\t<th>작성자</th>\r\n");
      out.write("\t\t\t\t\t\t<th>작성일</th>\r\n");
      out.write("\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t \t");

			 		List<ReplyVO> list = (List<ReplyVO>)request.getAttribute("replyView");
			 		int count = list.size();
			 		for(ReplyVO replyVo : list) {
			 	
      out.write("\r\n");
      out.write("\t\t\t \t\t<tr>\r\n");
      out.write("\t\t\t \t\t\t<td>");
      out.print(count );
      out.write("</td>\r\n");
      out.write("\t\t\t \t\t\t<td class = \"title\" >");
      out.print(replyVo.getReply_cont() );
      out.write("</td>\r\n");
      out.write("\t\t\t \t\t\t<td>");
      out.print(replyVo.getNick_name() );
      out.write("</td>\r\n");
      out.write("\t\t\t \t\t\t<td class = \"date\">");
      out.print(replyVo.getReply_date() );
      out.write("\r\n");
      out.write("\t\t\t \t\t\t");

							if(memberVo != null && replyVo.getMem_no() == memberVo.getMem_no()){
						
      out.write("\r\n");
      out.write("\t\t\t \t\t\t<td class = \"ox\"><a href = \"");
      out.print(request.getContextPath() );
      out.write("/board/ReplyDelete.do?board_no=");
      out.print(request.getAttribute("board_no"));
      out.write("&post_no=");
      out.print(request.getAttribute("post_no"));
      out.write("&reply_no=");
      out.print(replyVo.getReply_no() );
      out.write("\">x</a></td>\r\n");
      out.write("\t\t\t \t\t\t");
 } else {
      out.write("\r\n");
      out.write("\t\t\t \t\t\t<td class = \"ox\"></td>\r\n");
      out.write("\t\t\t \t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t \t\t</tr>\r\n");
      out.write("\t\t\t \t");
		
			 			count--;
			 		}
			 	
      out.write("\r\n");
      out.write("\t\t\t \t</table>\r\n");
      out.write("\t\t\t \t</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t \t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t<footer class=\"footer\">\r\n");
      out.write("\t\t<div class=\"ul\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>러닝마켓</li>\r\n");
      out.write("\t\t\t\t<li>LM소개</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"ul\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a>고객센터</a></li>\r\n");
      out.write("\t\t\t\t<li>이용약관</li>\r\n");
      out.write("\t\t\t\t<li>개인정보취급방침</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"ul\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a src=\"\">커뮤니티</a></li>\r\n");
      out.write("\t\t\t\t<li>묻고답하기</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<br> <br> <br> <br>\r\n");
      out.write("\t\t<p class=\"made\">\r\n");
      out.write("\t\t\tLearning Made By <a href=\"https://www.w3schools.com\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"tooltip\" title=\"Visit w3schools\">대덕인재개발원</a>\r\n");
      out.write("\t\t\t(주)Learning Market 사업자 정보<br> (주)Learning Market | 대표자 : 유동기\r\n");
      out.write("\t\t\t|사업자번호 : 000-0000-0000 사업자 정보 확인 | 개인정보보호책임자 : 유동기 | 통신판매업\r\n");
      out.write("\t\t\t:2020-중구대흥동 A-0001<br> 주소 : 대전광역시 중구 대흥동 500 영민빌딩 4층 402호 | 이메일\r\n");
      out.write("\t\t\t: Learning Market@korea.com<br>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
